
# this is a test
POST https://leobot.leocdp.com/event-game/put HTTP/1.1
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
content-type: application/json

{
  "utmdata": {
    "utmsource": "",
    "utmmedium": "",
    "utmcampaign": "",
    "utmterm": "",
    "utmcontent": ""
  },
  "payload": {
    "datetime": "2024-12-26T02:14:04.694Z",
    "obsid": "4KaMq3UZcLbx7HMoK5fgYL",
    "mediahost": "example.com",
    "tprefurl": "https://example.com/game-tracking/",
    "tprefdomain": "example.com",
    "tpurl": "https://example.com/game-tracking/test-game-2.html",
    "tpname": "Game 2- Vòng quay may mắn",
    "metric": "page-view",
    "eventdata": {
      "phone": "",
      "first_name": "",
      "living_district": "",
      "living_city": "",
      "marital_status" : "single",
      "personal_interests": [],
      "gift_code": ""
    },
    "visid": "7438b8df-5a3e-45cd-8099-9efa7617778e",
    "fgp": "TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTMxLjAuMC4wIFNhZmFyaS81MzcuMzYtMTY4MHgxMDUwLThmMjkxYTVkLWM2ZWYtNDZhNy05N2M0LTQxZWI0OTg1Y2EwMg==",
    "ctxsk": "8f291a5d-c6ef-46a7-97c4-41eb4985ca02"
  }
}